
package pws.hw2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PriceOutputImplService", targetNamespace = "http://hw2.pws/", wsdlLocation = "http://localhost:8082/PriceOutput/priceoutput?wsdl")
public class PriceOutputImplService
    extends Service
{

    private final static URL PRICEOUTPUTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRICEOUTPUTIMPLSERVICE_EXCEPTION;
    private final static QName PRICEOUTPUTIMPLSERVICE_QNAME = new QName("http://hw2.pws/", "PriceOutputImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/PriceOutput/priceoutput?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRICEOUTPUTIMPLSERVICE_WSDL_LOCATION = url;
        PRICEOUTPUTIMPLSERVICE_EXCEPTION = e;
    }

    public PriceOutputImplService() {
        super(__getWsdlLocation(), PRICEOUTPUTIMPLSERVICE_QNAME);
    }

    public PriceOutputImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRICEOUTPUTIMPLSERVICE_QNAME, features);
    }

    public PriceOutputImplService(URL wsdlLocation) {
        super(wsdlLocation, PRICEOUTPUTIMPLSERVICE_QNAME);
    }

    public PriceOutputImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRICEOUTPUTIMPLSERVICE_QNAME, features);
    }

    public PriceOutputImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PriceOutputImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PriceOutputImpl
     */
    @WebEndpoint(name = "PriceOutputImplPort")
    public PriceOutputImpl getPriceOutputImplPort() {
        return super.getPort(new QName("http://hw2.pws/", "PriceOutputImplPort"), PriceOutputImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PriceOutputImpl
     */
    @WebEndpoint(name = "PriceOutputImplPort")
    public PriceOutputImpl getPriceOutputImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hw2.pws/", "PriceOutputImplPort"), PriceOutputImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRICEOUTPUTIMPLSERVICE_EXCEPTION!= null) {
            throw PRICEOUTPUTIMPLSERVICE_EXCEPTION;
        }
        return PRICEOUTPUTIMPLSERVICE_WSDL_LOCATION;
    }

}
