//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.02 at 03:33:49 PM CET 
//


package pws.hw1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pws.hw1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pws.hw1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link Profile.RecommendedJobs }
     * 
     */
    public Profile.RecommendedJobs createProfileRecommendedJobs() {
        return new Profile.RecommendedJobs();
    }

    /**
     * Create an instance of {@link Profile.References }
     * 
     */
    public Profile.References createProfileReferences() {
        return new Profile.References();
    }

    /**
     * Create an instance of {@link Profile.Employments }
     * 
     */
    public Profile.Employments createProfileEmployments() {
        return new Profile.Employments();
    }

    /**
     * Create an instance of {@link Profile.Education }
     * 
     */
    public Profile.Education createProfileEducation() {
        return new Profile.Education();
    }

    /**
     * Create an instance of {@link Profile.Education.AcademicRecord }
     * 
     */
    public Profile.Education.AcademicRecord createProfileEducationAcademicRecord() {
        return new Profile.Education.AcademicRecord();
    }

    /**
     * Create an instance of {@link Profile.Keywords }
     * 
     */
    public Profile.Keywords createProfileKeywords() {
        return new Profile.Keywords();
    }

    /**
     * Create an instance of {@link Profile.DesiredCompanies }
     * 
     */
    public Profile.DesiredCompanies createProfileDesiredCompanies() {
        return new Profile.DesiredCompanies();
    }

    /**
     * Create an instance of {@link Profile.DesiredJobType }
     * 
     */
    public Profile.DesiredJobType createProfileDesiredJobType() {
        return new Profile.DesiredJobType();
    }

    /**
     * Create an instance of {@link Profile.RecommendedJobs.Job }
     * 
     */
    public Profile.RecommendedJobs.Job createProfileRecommendedJobsJob() {
        return new Profile.RecommendedJobs.Job();
    }

    /**
     * Create an instance of {@link Profile.References.Reference }
     * 
     */
    public Profile.References.Reference createProfileReferencesReference() {
        return new Profile.References.Reference();
    }

    /**
     * Create an instance of {@link Profile.Employments.Employment }
     * 
     */
    public Profile.Employments.Employment createProfileEmploymentsEmployment() {
        return new Profile.Employments.Employment();
    }

    /**
     * Create an instance of {@link Profile.Education.AcademicRecord.Courses }
     * 
     */
    public Profile.Education.AcademicRecord.Courses createProfileEducationAcademicRecordCourses() {
        return new Profile.Education.AcademicRecord.Courses();
    }

}
