
package pws.hw2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PriceOutput", targetNamespace = "http://hw2.pws/", wsdlLocation = "file:/home/andreas/Development/programming-web-services/deliverables-hw2/service/wsdl/PriceOutput.wsdl")
public class PriceOutput_Service
    extends Service
{

    private final static URL PRICEOUTPUT_WSDL_LOCATION;
    private final static WebServiceException PRICEOUTPUT_EXCEPTION;
    private final static QName PRICEOUTPUT_QNAME = new QName("http://hw2.pws/", "PriceOutput");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/andreas/Development/programming-web-services/deliverables-hw2/service/wsdl/PriceOutput.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRICEOUTPUT_WSDL_LOCATION = url;
        PRICEOUTPUT_EXCEPTION = e;
    }

    public PriceOutput_Service() {
        super(__getWsdlLocation(), PRICEOUTPUT_QNAME);
    }

    public PriceOutput_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRICEOUTPUT_QNAME, features);
    }

    public PriceOutput_Service(URL wsdlLocation) {
        super(wsdlLocation, PRICEOUTPUT_QNAME);
    }

    public PriceOutput_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRICEOUTPUT_QNAME, features);
    }

    public PriceOutput_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PriceOutput_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PriceOutput
     */
    @WebEndpoint(name = "PriceOutputPort")
    public PriceOutput getPriceOutputPort() {
        return super.getPort(new QName("http://hw2.pws/", "PriceOutputPort"), PriceOutput.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PriceOutput
     */
    @WebEndpoint(name = "PriceOutputPort")
    public PriceOutput getPriceOutputPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hw2.pws/", "PriceOutputPort"), PriceOutput.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRICEOUTPUT_EXCEPTION!= null) {
            throw PRICEOUTPUT_EXCEPTION;
        }
        return PRICEOUTPUT_WSDL_LOCATION;
    }

}
