
package pws.hw2;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PriceOutput", targetNamespace = "http://hw2.pws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PriceOutput {


    /**
     * 
     * @param availableItinerary
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "priceOutput", targetNamespace = "http://hw2.pws/", className = "pws.hw2.PriceOutput_Type")
    @ResponseWrapper(localName = "priceOutputResponse", targetNamespace = "http://hw2.pws/", className = "pws.hw2.PriceOutputResponse")
    @Action(input = "http://hw2.pws/PriceOutput/priceOutput", output = "http://hw2.pws/PriceOutput/priceOutputResponse")
    public List<Integer> priceOutput(
        @WebParam(name = "availableItinerary", targetNamespace = "")
        List<Itinerary> availableItinerary);

}
