
package pws.hw2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TicketIssue", targetNamespace = "http://hw2.pws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TicketIssue {


    /**
     * 
     * @param ticket
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ticketIssue", targetNamespace = "http://hw2.pws/", className = "pws.hw2.TicketIssue_Type")
    @ResponseWrapper(localName = "ticketIssueResponse", targetNamespace = "http://hw2.pws/", className = "pws.hw2.TicketIssueResponse")
    @Action(input = "http://hw2.pws/TicketIssue/ticketIssue", output = "http://hw2.pws/TicketIssue/ticketIssueResponse")
    public boolean ticketIssue(
        @WebParam(name = "ticket", targetNamespace = "")
        Ticket ticket);

}
