
package pws.hw2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TicketIssue", targetNamespace = "http://hw2.pws/", wsdlLocation = "file:/home/andreas/Development/programming-web-services/deliverables-hw2/service/wsdl/TicketIssue.wsdl")
public class TicketIssue_Service
    extends Service
{

    private final static URL TICKETISSUE_WSDL_LOCATION;
    private final static WebServiceException TICKETISSUE_EXCEPTION;
    private final static QName TICKETISSUE_QNAME = new QName("http://hw2.pws/", "TicketIssue");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/andreas/Development/programming-web-services/deliverables-hw2/service/wsdl/TicketIssue.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TICKETISSUE_WSDL_LOCATION = url;
        TICKETISSUE_EXCEPTION = e;
    }

    public TicketIssue_Service() {
        super(__getWsdlLocation(), TICKETISSUE_QNAME);
    }

    public TicketIssue_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TICKETISSUE_QNAME, features);
    }

    public TicketIssue_Service(URL wsdlLocation) {
        super(wsdlLocation, TICKETISSUE_QNAME);
    }

    public TicketIssue_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TICKETISSUE_QNAME, features);
    }

    public TicketIssue_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TicketIssue_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TicketIssue
     */
    @WebEndpoint(name = "TicketIssuePort")
    public TicketIssue getTicketIssuePort() {
        return super.getPort(new QName("http://hw2.pws/", "TicketIssuePort"), TicketIssue.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TicketIssue
     */
    @WebEndpoint(name = "TicketIssuePort")
    public TicketIssue getTicketIssuePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hw2.pws/", "TicketIssuePort"), TicketIssue.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TICKETISSUE_EXCEPTION!= null) {
            throw TICKETISSUE_EXCEPTION;
        }
        return TICKETISSUE_WSDL_LOCATION;
    }

}
