
package pws.hw2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TicketBooking", targetNamespace = "http://hw2.pws/", wsdlLocation = "file:/home/andreas/Development/programming-web-services/deliverables-hw2/service/wsdl/TicketBooking.wsdl")
public class TicketBooking_Service
    extends Service
{

    private final static URL TICKETBOOKING_WSDL_LOCATION;
    private final static WebServiceException TICKETBOOKING_EXCEPTION;
    private final static QName TICKETBOOKING_QNAME = new QName("http://hw2.pws/", "TicketBooking");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/andreas/Development/programming-web-services/deliverables-hw2/service/wsdl/TicketBooking.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TICKETBOOKING_WSDL_LOCATION = url;
        TICKETBOOKING_EXCEPTION = e;
    }

    public TicketBooking_Service() {
        super(__getWsdlLocation(), TICKETBOOKING_QNAME);
    }

    public TicketBooking_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TICKETBOOKING_QNAME, features);
    }

    public TicketBooking_Service(URL wsdlLocation) {
        super(wsdlLocation, TICKETBOOKING_QNAME);
    }

    public TicketBooking_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TICKETBOOKING_QNAME, features);
    }

    public TicketBooking_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TicketBooking_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TicketBooking
     */
    @WebEndpoint(name = "TicketBookingPort")
    public TicketBooking getTicketBookingPort() {
        return super.getPort(new QName("http://hw2.pws/", "TicketBookingPort"), TicketBooking.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TicketBooking
     */
    @WebEndpoint(name = "TicketBookingPort")
    public TicketBooking getTicketBookingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hw2.pws/", "TicketBookingPort"), TicketBooking.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TICKETBOOKING_EXCEPTION!= null) {
            throw TICKETBOOKING_EXCEPTION;
        }
        return TICKETBOOKING_WSDL_LOCATION;
    }

}
